spring:
  application:
    name: backend # Nombre de la aplicación

  datasource:
    url: jdbc:postgresql://localhost:5432/gpi_basededatos # Cambia si usas otro host o servicio Docker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10 # Ajuste del pool de conexiones

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Dialecto para PostgreSQL
    hibernate:
      ddl-auto: update # Mantiene los datos entre reinicios
    show-sql: true # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        format_sql: true # Formatea las consultas SQL en la consola

  sql:
    init:
      mode: always # Ejecuta scripts de inicialización si están disponibles

springdoc:
  swagger-ui:
    path: /swagger # Acceso en: http://localhost:8080/swagger
    operationsSorter: method # Ordena los endpoints por método HTTP
  api-docs:
    path: /api-docs # Documentación OpenAPI en JSON: http://localhost:8080/api-docs
  show-actuator: true # Permite visualizar los endpoints de Actuator si están activados

server:
  port: 8080 # Puerto en el que se ejecuta la aplicación
