spring:
  application:
    name: backend # Nombre de la aplicación

  datasource:
    url: jdbc:h2:file:./data/gpi-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE # H2 persistente en archivo
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 10 # Ajuste del pool de conexiones

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Dialecto para H2
    hibernate:
      ddl-auto: update # Mantiene los datos entre reinicios
    show-sql: true # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        format_sql: true # Formatea las consultas SQL en la consola

  h2:
    console:
      enabled: true # Habilita la consola H2
      path: /h2-console # Acceso en: http://localhost:8080/h2-console

  sql:
    init:
      mode: always # Ejecuta scripts de inicialización en H2 si existen

springdoc:
  swagger-ui:
    path: /swagger # Acceso en: http://localhost:8080/swagger
    operationsSorter: method # Ordena los endpoints por método HTTP
  api-docs:
    path: /api-docs # Documentación OpenAPI en JSON: http://localhost:8080/api-docs
  show-actuator: true # Permite visualizar los endpoints de Actuator si están activados

server:
  port: 8080 # Puerto en el que se ejecuta la aplicación
